import tkinter as tk
from tkinter import ttk
import pandas as pd
import numpy as np
import sklearn

def estimate_score():
    pass

def compile_row_for_model():
    pass

root = tk.Tk()
root.title("Umazing calculator")
root.geometry("1100x500")
#icon = tk.PhotoImage(file='icon.png')
#root.iconphoto(False, icon)
score_result = tk.StringVar(root, value='XXXXX')
letter_result = tk.StringVar(root, value='G+')

root.grid_columnconfigure(0, weight=2)
root.grid_columnconfigure(1, weight=1)
root.grid_columnconfigure(2, weight=2)
root.grid_columnconfigure(3, weight=1)
root.grid_columnconfigure(4, weight=2)
root.grid_columnconfigure(5, weight=1)
root.grid_columnconfigure(6, weight=2)
root.grid_columnconfigure(7, weight=1)

root.grid_rowconfigure(0, weight=1)
root.grid_rowconfigure(1, weight=1)
root.grid_rowconfigure(2, weight=1)
root.grid_rowconfigure(3, weight=1)
root.grid_rowconfigure(4, weight=1)
root.grid_rowconfigure(5, weight=1)
root.grid_rowconfigure(6, weight=1)
root.grid_rowconfigure(7, weight=1)
root.grid_rowconfigure(8, weight=1)
root.grid_rowconfigure(9, weight=1)
root.grid_rowconfigure(10, weight=1)

spd_label = ttk.Label(root, text="SPD")
spd_label.grid(column=0, row=1, sticky='nsew')
sta_label = ttk.Label(root, text="STA")
sta_label.grid(column=0, row=2, sticky='nsew')
pwr_label = ttk.Label(root, text="PWR")
pwr_label.grid(column=0, row=3, sticky='nsew')
guts_label = ttk.Label(root, text="GUTS")
guts_label.grid(column=0, row=4, sticky='nsew')
wit_label = ttk.Label(root, text="WIT")
wit_label.grid(column=0, row=5, sticky='nsew')
ult_lvl_label = ttk.Label(root, text="LVL of Ult")
ult_lvl_label.grid(column=0, row=6, sticky='nsew')
inherited_ult_label = ttk.Label(root, text="Inherited Ults Count")
inherited_ult_label.grid(column=0, row=7, sticky='nsew')
fans_label = ttk.Label(root, text="№ of FANS")
fans_label.grid(column=0, row=8, sticky='nsew')
preopw_label = ttk.Label(root, text="Побед в PreOP")
preopw_label.grid(column=0, row=9, sticky='nsew')

spd_entry = ttk.Entry(root)
spd_entry.insert(0, "100")
spd_entry.grid(column=1, row=1, sticky='nsew')
sta_entry = ttk.Entry(root)
sta_entry.insert(0, "100")
sta_entry.grid(column=1, row=2, sticky='nsew')
pwr_entry = ttk.Entry(root)
pwr_entry.insert(0, "100")
pwr_entry.grid(column=1, row=3, sticky='nsew')
guts_entry = ttk.Entry(root)
guts_entry.insert(0, "100")
guts_entry.grid(column=1, row=4, sticky='nsew')
wit_entry = ttk.Entry(root)
wit_entry.insert(0, "100")
wit_entry.grid(column=1, row=5, sticky='nsew')
ult_lvl_entry = ttk.Entry(root)
ult_lvl_entry.insert(0, "1")
ult_lvl_entry.grid(column=1, row=6, sticky='nsew')
inherited_ult_entry = ttk.Entry(root)
inherited_ult_entry.insert(0, "2")
inherited_ult_entry.grid(column=1, row=7, sticky='nsew')
fans_entry = ttk.Entry(root)
fans_entry.insert(0, "10000")
fans_entry.grid(column=1, row=8, sticky='nsew')
preopw_spin = ttk.Spinbox(root, from_=0, to=60, state='readonly')
preopw_spin.grid(column=1, row=9, sticky='nsew')

g1w_label = ttk.Label(root, text="Побед в G1")
g1w_label.grid(column=2, row=1, sticky='nsew')
g2w_label = ttk.Label(root, text="Побед в G2")
g2w_label.grid(column=2, row=2, sticky='nsew')
g3w_label = ttk.Label(root, text="Побед в G3")
g3w_label.grid(column=2, row=3, sticky='nsew')
opw_label = ttk.Label(root, text="Побед в OPW")
opw_label.grid(column=2, row=4, sticky='nsew')
exw_label = ttk.Label(root, text="Побед в EX")
exw_label.grid(column=2, row=5, sticky='nsew')
g1p_label = ttk.Label(root, text="Призовых (2-5) в G1")
g1p_label.grid(column=2, row=6, sticky='nsew')
g2p_label = ttk.Label(root, text="Призовых (2-5) в G2")
g2p_label.grid(column=2, row=7, sticky='nsew')
g3p_label = ttk.Label(root, text="Призовых (2-5) в G3")
g3p_label.grid(column=2, row=8, sticky='nsew')
exp_label = ttk.Label(root, text="Призовых (2-5) в EX")
exp_label.grid(column=2, row=9, sticky='nsew')

g1w_spin = ttk.Spinbox(root, from_=0, to=60, state='readonly')
g1w_spin.grid(column=3, row=1, sticky='nsew')
g2w_spin = ttk.Spinbox(root, from_=0, to=60, state='readonly')
g2w_spin.grid(column=3, row=2, sticky='nsew')
g3w_spin = ttk.Spinbox(root, from_=0, to=60, state='readonly')
g3w_spin.grid(column=3, row=3, sticky='nsew')
opw_spin = ttk.Spinbox(root, from_=0, to=60, state='readonly')
opw_spin.grid(column=3, row=4, sticky='nsew')
exw_spin = ttk.Spinbox(root, from_=0, to=3, state='readonly')
exw_spin.grid(column=3, row=5, sticky='nsew')
g1p_spin = ttk.Spinbox(root, from_=0, to=60, state='readonly')
g1p_spin.grid(column=3, row=6, sticky='nsew')
g2p_spin = ttk.Spinbox(root, from_=0, to=60, state='readonly')
g2p_spin.grid(column=3, row=7, sticky='nsew')
g3p_spin = ttk.Spinbox(root, from_=0, to=60, state='readonly')
g3p_spin.grid(column=3, row=8, sticky='nsew')
exp_spin = ttk.Spinbox(root, from_=0, to=3, state='readonly')
exp_spin.grid(column=3, row=9, sticky='nsew')

turf_label = ttk.Label(root, text="Turf Aptitude")
turf_label.grid(column=4, row=0, sticky='nsew')
sprint_label = ttk.Label(root, text="Sprint Aptitude")
sprint_label.grid(column=4, row=1, sticky='nsew')
mile_label = ttk.Label(root, text="Mile Aptitude")
mile_label.grid(column=4, row=2, sticky='nsew')
medium_label = ttk.Label(root, text="Medium Aptitude")
medium_label.grid(column=4, row=3, sticky='nsew')
long_label = ttk.Label(root, text="Long Aptitude")
long_label.grid(column=4, row=4, sticky='nsew')

dirt_label = ttk.Label(root, text="Dirt Aptitude")
dirt_label.grid(column=6, row=0, sticky='nsew')
front_label = ttk.Label(root, text="Front Runner Aptitude")
front_label.grid(column=6, row=1, sticky='nsew')
pacer_label = ttk.Label(root, text="Pace Chaser Aptitude")
pacer_label.grid(column=6, row=2, sticky='nsew')
late_label = ttk.Label(root, text="Late Surger Aptitude")
late_label.grid(column=6, row=3, sticky='nsew')
end_label = ttk.Label(root, text="End Closer Aptitude")
end_label.grid(column=6, row=4, sticky='nsew')

aptitudes_list = ['S', 'A', 'B', 'C', 'D', 'E', 'F', 'G']

turf_spin = ttk.Spinbox(root, values=aptitudes_list, state='readonly')
turf_spin.grid(column=5, row=0, sticky='nsew')
sprint_spin = ttk.Spinbox(root, values=aptitudes_list, state='readonly')
sprint_spin.grid(column=5, row=1, sticky='nsew')
mile_spin = ttk.Spinbox(root, values=aptitudes_list, state='readonly')
mile_spin.grid(column=5, row=2, sticky='nsew')
medium_spin = ttk.Spinbox(root, values=aptitudes_list, state='readonly')
medium_spin.grid(column=5, row=3, sticky='nsew')
long_spin = ttk.Spinbox(root, values=aptitudes_list, state='readonly')
long_spin.grid(column=5, row=4, sticky='nsew')

dirt_spin = ttk.Spinbox(root, values=aptitudes_list, state='readonly')
dirt_spin.grid(column=7, row=0, sticky='nsew')
front_spin = ttk.Spinbox(root, values=aptitudes_list, state='readonly')
front_spin.grid(column=7, row=1, sticky='nsew')
pacer_spin = ttk.Spinbox(root, values=aptitudes_list, state='readonly')
pacer_spin.grid(column=7, row=2, sticky='nsew')
late_spin = ttk.Spinbox(root, values=aptitudes_list, state='readonly')
late_spin.grid(column=7, row=3, sticky='nsew')
end_spin = ttk.Spinbox(root, values=aptitudes_list, state='readonly')
end_spin.grid(column=7, row=4, sticky='nsew')

green_skills_label = ttk.Label(root, text="Green Skills")
green_skills_label.grid(column=4, row=5, sticky='nsew')
sprint_skills_label = ttk.Label(root, text="Sprint Skills")
sprint_skills_label.grid(column=4, row=6, sticky='nsew')
mile_skills_label = ttk.Label(root, text="Mile Skills")
mile_skills_label.grid(column=4, row=7, sticky='nsew')
medium_skills_label = ttk.Label(root, text="Medium Skills")
medium_skills_label.grid(column=4, row=8, sticky='nsew')
long_skills_label = ttk.Label(root, text="Long Skills")
long_skills_label.grid(column=4, row=9, sticky='nsew')

common_skills_label = ttk.Label(root, text="Common Skills")
common_skills_label.grid(column=6, row=5, sticky='nsew')
front_skills_label = ttk.Label(root, text="Front Runner Skills")
front_skills_label.grid(column=6, row=6, sticky='nsew')
pacer_skills_label = ttk.Label(root, text="Pace Chaser Skills")
pacer_skills_label.grid(column=6, row=7, sticky='nsew')
late_skills_label = ttk.Label(root, text="Late Surger Skills")
late_skills_label.grid(column=6, row=8, sticky='nsew')
end_skills_label = ttk.Label(root, text="End Closer Skills")
end_skills_label.grid(column=6, row=9, sticky='nsew')

green_skills_spin = ttk.Spinbox(root, from_=0.0, to=20.0, increment=0.5, state='readonly')
green_skills_spin.grid(column=5, row=5, sticky='nsew')
sprint_skills_spin = ttk.Spinbox(root, from_=0.0, to=20.0, increment=0.5, state='readonly')
sprint_skills_spin.grid(column=5, row=6, sticky='nsew')
mile_skills_spin = ttk.Spinbox(root, from_=0.0, to=20.0, increment=0.5, state='readonly')
mile_skills_spin.grid(column=5, row=7, sticky='nsew')
medium_skills_spin = ttk.Spinbox(root, from_=0.0, to=20.0, increment=0., state='readonly')
medium_skills_spin.grid(column=5, row=8, sticky='nsew')
long_skills_spin = ttk.Spinbox(root, from_=0.0, to=20.0, increment=0.5, state='readonly')
long_skills_spin.grid(column=5, row=9, sticky='nsew')

common_skills_spin = ttk.Spinbox(root, from_=0.0, to=20.0, increment=0.5, state='readonly')
common_skills_spin.grid(column=7, row=5, sticky='nsew')
front_skills_spin = ttk.Spinbox(root, from_=0.0, to=20.0, increment=0.5, state='readonly')
front_skills_spin.grid(column=7, row=6, sticky='nsew')
pacer_skills_spin = ttk.Spinbox(root, from_=0.0, to=20.0, increment=0., state='readonly')
pacer_skills_spin.grid(column=7, row=7, sticky='nsew')
late_skills_spin = ttk.Spinbox(root, from_=0.0, to=20.0, increment=0.5, state='readonly')
late_skills_spin.grid(column=7, row=8, sticky='nsew')
end_skills_spin = ttk.Spinbox(root, from_=0.0, to=20.0, increment=0.5, state='readonly')
end_skills_spin.grid(column=7, row=9, sticky='nsew')

deco_frame = ttk.LabelFrame(root, text='Inference')
deco_frame.grid(column=0, row=0, columnspan=4, sticky='nsew')
deco_frame.grid_columnconfigure(0, weight=1)
deco_frame.grid_columnconfigure(1, weight=1)
deco_frame.grid_columnconfigure(2, weight=1)
deco_frame.grid_columnconfigure(3, weight=1)
deco_frame.grid_rowconfigure(0, weight=1)

est_button = ttk.Button(deco_frame, text='Рассчитать!', command=estimate_score)
est_button.grid(column=0, row=0, sticky='nsew')

res_label = ttk.Label(deco_frame, text='Ожидаемый результат:')
res_label.grid(column=1, row=0, sticky='nsew')

score_label = ttk.Label(deco_frame, textvariable=score_result)
score_label.grid(column=2, row=0, sticky='nsew')

letter_label = ttk.Label(deco_frame, textvariable=letter_result)
letter_label.grid(column=3, row=0, sticky='nsew')

root.mainloop()